In [11]:
import pandas as pd
import os
import datetime

In [12]:
def get_latest_json_file(directory):
    # Get a list of all JSON files in the directory
    json_files = [os.path.join(directory, f) for f in os.listdir(directory) if f.endswith('.json') and os.path.isfile(os.path.join(directory, f))]
    
    # Check if there are any JSON files in the directory
    if not json_files:
        return None, None
    
    # Get the latest JSON file based on modification time
    latest_file = max(json_files, key=os.path.getmtime)
    
    return latest_file

In [3]:
directory = '/home/ngocthang/Documents/Code/Stock-Company-Analysis/backend/data/raw/markets'
for f in os.listdir(directory):
    #if f.endswith('.json') and os.path.isfile(os.path.join(directory, f))
    print(os.path.join(directory, f))

/home/ngocthang/Documents/Code/Stock-Company-Analysis/backend/data/raw/markets/data_markets_2024_06_17.json
/home/ngocthang/Documents/Code/Stock-Company-Analysis/backend/data/raw/markets/data_markets_2024_06_16.json

## _COMPANY_

### READ FILE

In [23]:
# Example usage
directory_path = '/home/ngocthang/Documents/Code/Stock-Company-Analysis/backend/data/raw/companies'
latest_file = get_latest_json_file(directory_path)

if latest_file:
    print(f"The latest JSON file is: {latest_file}")
else:
    print("The directory is empty or contains no JSON files.")

The latest JSON file is: /home/ngocthang/Documents/Code/Stock-Company-Analysis/backend/data/raw/companies/data_companies_2024_06_17.json

### TRANSFORM

In [24]:
import pandas as pd
import numpy as np

In [25]:
df = pd.read_json(latest_file)
df.head()

,name,ticker,cik,cusip,exchange,isDelisted,category,sector,industry,sic,sicSector,sicIndustry,famaSector,famaIndustry,currency,location,id
0,ADMIRALTY BANCORP INC,AAAB,1066808,007231103,NASDAQ,True,Domestic Common Stock,Financial Services,Banks - Regional,6022,Finance Insurance And Real Estate,State Commercial Banks,,Banking,USD,Florida; U.S.A,3daf92ec6639eede5c282d6cd20f8342
1,ADVANCED ACCELERATOR APPLICATIONS SA,AAAP,1611787,00790T100,NASDAQ,True,ADR Common Stock,Healthcare,Biotechnology,2834,Manufacturing,Pharmaceutical Preparations,,Pharmaceutical Products,EUR,France,cf1185a716b218ee7db7d812695108eb
2,ACCESS ANYTIME BANCORP INC,AABC,1024015,00431F105,NASDAQ,True,Domestic Common Stock,Financial Services,Banks - Regional,6035,Finance Insurance And Real Estate,Savings Institution Federally Chartered,,Banking,USD,New Mexico; U.S.A,800e1a7171119770ea03175a8f58830a
3,ALLIANCE ATLANTIS COMMUNICATIONS INC,AACB,1005887,01853E204 01855R302,NASDAQ,True,Canadian Common Stock,Communication Services,Entertainment,7812,Services,Services-Motion Picture & Video Tape Production,,Entertainment,CAD,Ontario; Canada,d3eb2f4a61137068856d2876cc3fe78b
4,ASSET ACCEPTANCE CAPITAL CORP,AACC,1264707,04543P100,NASDAQ,True,Domestic Common Stock,Financial Services,Asset Management,6153,Finance Insurance And Real Estate,Short-Term Business Credit Institutions,,Banking,USD,Michigan; U.S.A,cee355397a974512760921762e03c30c

In [26]:
len(df)

28228

In [31]:
id = df['id']
print(len(id))
id.head()

28228

0    3daf92ec6639eede5c282d6cd20f8342
1    cf1185a716b218ee7db7d812695108eb
2    800e1a7171119770ea03175a8f58830a
3    d3eb2f4a61137068856d2876cc3fe78b
4    cee355397a974512760921762e03c30c
Name: id, dtype: object

In [30]:
id = id.drop_duplicates()
print(len(id))

28228

In [32]:
df = df.replace(r'^\s*$', np.nan, regex=True).drop_duplicates().dropna()

/tmp/ipykernel_4671/3804594421.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r'^\s*$', np.nan, regex=True).drop_duplicates().dropna()

In [33]:
len(df)

0

In [23]:
df[df['sicIndustry'] == "Banking"].head(10)

Empty DataFrame
Columns: [name, ticker, cik, cusip, exchange, isDelisted, category, sector, industry, sic, sicSector, sicIndustry, famaSector, famaIndustry, currency, location, id]
Index: []

In [31]:
df_na = df.dropna()

In [36]:
print(len(df))
print(len(df_new))

28221
0

In [26]:
df.head()

,name,ticker,cik,cusip,exchange,isDelisted,category,sector,industry,sic,sicSector,sicIndustry,famaSector,famaIndustry,currency,location,id
0,ADMIRALTY BANCORP INC,AAAB,1066808,007231103,NASDAQ,True,Domestic Common Stock,Financial Services,Banks - Regional,6022,Finance Insurance And Real Estate,State Commercial Banks,,Banking,USD,Florida; U.S.A,3daf92ec6639eede5c282d6cd20f8342
1,ADVANCED ACCELERATOR APPLICATIONS SA,AAAP,1611787,00790T100,NASDAQ,True,ADR Common Stock,Healthcare,Biotechnology,2834,Manufacturing,Pharmaceutical Preparations,,Pharmaceutical Products,EUR,France,cf1185a716b218ee7db7d812695108eb
2,ACCESS ANYTIME BANCORP INC,AABC,1024015,00431F105,NASDAQ,True,Domestic Common Stock,Financial Services,Banks - Regional,6035,Finance Insurance And Real Estate,Savings Institution Federally Chartered,,Banking,USD,New Mexico; U.S.A,800e1a7171119770ea03175a8f58830a
3,ALLIANCE ATLANTIS COMMUNICATIONS INC,AACB,1005887,01853E204 01855R302,NASDAQ,True,Canadian Common Stock,Communication Services,Entertainment,7812,Services,Services-Motion Picture & Video Tape Production,,Entertainment,CAD,Ontario; Canada,d3eb2f4a61137068856d2876cc3fe78b
4,ASSET ACCEPTANCE CAPITAL CORP,AACC,1264707,04543P100,NASDAQ,True,Domestic Common Stock,Financial Services,Asset Management,6153,Finance Insurance And Real Estate,Short-Term Business Credit Institutions,,Banking,USD,Michigan; U.S.A,cee355397a974512760921762e03c30c

# _MARKETS_

## READ

In [13]:
# Example usage
directory_path = '/home/ngocthang/Documents/Code/Stock-Company-Analysis/backend/data/raw/markets'
latest_file = get_latest_json_file(directory_path)

if latest_file:
    print(f"The latest JSON file is: {latest_file}")
else:
    print("The directory is empty or contains no JSON files.")

The latest JSON file is: /home/ngocthang/Documents/Code/Stock-Company-Analysis/backend/data/raw/markets/data_markets_2024_06_17.json

In [14]:
df_markets = pd.read_json(latest_file)
print(len(df_markets))

16

In [15]:
df_markets.head()

,market_type,region,primary_exchanges,local_open,local_close,current_status,notes
0,Equity,United States,"NASDAQ, NYSE, AMEX, BATS",09:30,16:15,closed,
1,Equity,Canada,"Toronto, Toronto Ventures",09:30,16:00,closed,
2,Equity,United Kingdom,London,08:00,16:30,closed,
3,Equity,Germany,"XETRA, Berlin, Frankfurt, Munich, Stuttgart",08:00,20:00,closed,
4,Equity,France,Paris,09:00,17:30,closed,

In [17]:
df_markets[['region', 'local_open', 'local_close']]

            region local_open local_close
0    United States      09:30       16:15
1           Canada      09:30       16:00
2   United Kingdom      08:00       16:30
3          Germany      08:00       20:00
4           France      09:00       17:30
5            Spain      09:00       17:30
6         Portugal      08:00       16:30
7            Japan      09:00       15:00
8            India      09:15       15:30
9   Mainland China      09:30       15:00
10       Hong Kong      09:30       16:00
11          Brazil      10:00       17:30
12          Mexico      08:30       15:00
13    South Africa      09:00       17:00
14          Global      00:00       23:59
15          Global      00:00       23:59

In [21]:
exchanges = df_markets[['region', 'primary_exchanges']]
exchanges['primary_exchanges'] = exchanges['primary_exchanges'].str.split(', ')
 # Explode the 'primary_exchanges' column into multiple rows
exchanges = exchanges.explode('primary_exchanges').reset_index(drop=True)

/tmp/ipykernel_4671/1634139314.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exchanges['primary_exchanges'] = exchanges['primary_exchanges'].str.split(', ')

In [22]:
exchanges.head()

          region primary_exchanges
0  United States            NASDAQ
1  United States              NYSE
2  United States              AMEX
3  United States              BATS
4         Canada           Toronto

In [10]:
df_transformed_company = pd.read_json(
    '/home/ngocthang/Documents/Code/Stock-Company-Analysis/backend/data/transformed/transformed_to_database_companies/transformed_companies_2024_06_19.json',
    lines=True
)

In [12]:
df_transformed_company.head()

,company_exchange,company_industry,company_sector,company_sic_id,company_name,company_ticket,company_is_delisted,company_category,company_currency,company_location
0,NASDAQ,Banks - Regional,Financial Services,6022,ADMIRALTY BANCORP INC,AAAB,True,Domestic Common Stock,USD,Florida; U.S.A
1,NASDAQ,Banks - Regional,Financial Services,6035,ACCESS ANYTIME BANCORP INC,AABC,True,Domestic Common Stock,USD,New Mexico; U.S.A
2,NASDAQ,Asset Management,Financial Services,6153,ASSET ACCEPTANCE CAPITAL CORP,AACC,True,Domestic Common Stock,USD,Michigan; U.S.A
3,NASDAQ,Credit Services,Financial Services,6099,ACE CASH EXPRESS INC,AACE,True,Domestic Common Stock,USD,Texas; U.S.A
4,NASDAQ,Shell Companies,Industrials,6770,ARMADA ACQUISITION CORP I,AACI,False,Domestic Common Stock Primary Class,USD,Pennsylvania; U.S.A

In [13]:
df_transformed_company[df_transformed_company["company_exchange"] != "NASDAQ"].head(10)

,company_exchange,company_industry,company_sector,company_sic_id,company_name,company_ticket,company_is_delisted,company_category,company_currency,company_location
13160,NYSE,Diagnostics & Research,Healthcare,3826,AGILENT TECHNOLOGIES INC,A,False,Domestic Common Stock,USD,California; U.S.A
13161,NYSE,Aluminum,Basic Materials,3334,ALCOA CORP,AA,False,Domestic Common Stock,USD,Pennsylvania; U.S.A
13162,NYSE,Shell Companies,Industrials,6770,ARES ACQUISITION CORP,AAC,True,Domestic Common Stock Primary Class,USD,New York; U.S.A
13163,NYSE,Asset Management,Financial Services,6153,ARCADIA FINANCIAL LTD,AAC1,True,Domestic Common Stock,USD,Minnesota; U.S.A
13164,NYSE,Medical Care Facilities,Healthcare,8093,AAC HOLDINGS INC,AACH,True,Domestic Common Stock,USD,Tennessee; U.S.A
13165,NYSE,Shell Companies,Industrials,6770,ARES ACQUISITION CORP II,AACT,False,Domestic Common Stock Primary Class,USD,New York; U.S.A
13166,NYSE,REIT - Mortgage,Real Estate,6798,AMBASSADOR APARTMENTS INC,AAH,True,Domestic Common Stock,USD,Illinois; U.S.A
13167,NYSE,REIT - Mortgage,Real Estate,6798,ARLINGTON ASSET INVESTMENT CORP,AAIC,True,Domestic Common Stock Primary Class,USD,Virginia; U.S.A
13168,NYSE,Airlines,Industrials,4512,AMR CORP,AAMRQ,True,Domestic Common Stock,USD,Texas; U.S.A
13169,NYSE,Rental & Leasing Services,Industrials,7359,AARON'S COMPANY INC,AAN,False,Domestic Common Stock,USD,Georgia; U.S.A

In [ ]:
df